<?php

namespace miercolesBundle\Repository;

/**
 * miercolesEntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class miercolesEntidadRepository extends \Doctrine\ORM\EntityRepository
{
}
